### ISSUE TITLE
PNG - Large diagram is cut off

### ISSUE THREAD

**Issue by yboujraf** [krisztianb/typedoc-umlclass#3]
Dear @krisztianb 

# PNG - umlClassDiagramFormat: 'png',

## Picture

When rendering class diagram, some uml is too large like and not renderized completely :

![image](https://user-images.githubusercontent.com/6151258/81496339-430fc980-92b7-11ea-8a8b-d6d34df0a778.png)

Best Regards,
Youssef

**Comment by krisztianb** [comment]
I looked this one up. This is a default limitation of PlantUML and not an issue with the plugin itself. It should be possible to bypass this by setting and environment variable on your computer: https://plantuml.com/faq#ta2awl095d7kka3pk8u1

Could you try that?

**Comment by yboujraf** [comment]
Dear @krisztianb 

Please share the settings I will try it. I have seen with svg, the image is not cut off.

Best Regards,
Youssef

**Comment by krisztianb** [comment]
Ok. I copied it from the page I linked, since the HTML anchor is no longer working?!

>I want to generate huge diagrams!
>
> PlantUML limits image width and height to 4096. There is a environment variable that you can set to override this limit: PLANTUML_LIMIT_SIZE. You have to define this variable before launching PlantUML, something like:
>
>set PLANTUML_LIMIT_SIZE=8192
>
>or
>
>setenv PLANTUML_LIMIT_SIZE 8192
>
>Another way is an option in the command line:
>
>java -DPLANTUML_LIMIT_SIZE=8192 -jar /path/to/plantuml.jar ...
>
>Note that if you generate very big diagrams, (for example, something like 20 000 x 10 000 pixels), you can have some memory issues. The solution is to add this parameter to the java vm : -Xmx1024m.

**Comment by krisztianb** [comment]
This should be resolved.

**Comment by yboujraf** [comment]
Dear @krisztianb 

The issue stills with png format.

Best Regards,
Youssef

**Comment by krisztianb** [comment]
Dear @yboujraf as you can see a few comments above this is not an issue with the plugin itself, but a default limitation in PlantUML. You should be able to resolve this by setting an environment varialbe on the computer.

By the way I'm thinking about dropping PNG support alltogehter. Because I don't see any benefits in having a pixel graphic format used for diagrams. The filesize is not smaller, you have this PlantUML limitation and it gets pixelated when resizing.

What do you thinking? Do you really need PNG graphics or can you use the SVG ones too?
